In [1]:
import numpy as np

In [3]:
two_qubit_groundstate = np.zeros(4)
two_qubit_groundstate[0] = 1
CNOT = np.array([
    [1,0,0,0],
    [0,1,0,0],
    [0,0,0,1],
    [0,0,1,0]
])

CNOT @ two_qubit_groundstate

array([1., 0., 0., 0.])

In [4]:
# But if we have one qubit at an excited state
two_qubit_state = np.zeros(4)
two_qubit_state[2] = 1
CNOT @ two_qubit_state

array([0., 0., 0., 1.])

In [10]:
# A |0><0| density matrix
ket = np.array([1, 0]).T
bra = ket.T.conj().copy()
np.kron(ket, bra).reshape(2, 2)

array([[1, 0],
       [0, 0]])